name: Sync package_control_channel

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add wbond https://github.com/wbond/package_control_channel.git
          git fetch wbond
          git branch -f package_control_channel wbond/master

      - name: Remove upstream workflows
        run: |
          git checkout package_control_channel
          rm -rf .github/workflows
          git commit -am "Remove upstream workflows" || echo "No changes to commit"

      - name: Push cleaned branch
        run: |
          git push origin package_control_channel --force
